name: invoice-manager
region: nyc
services:
  - name: backend
    image:
      registry_type: DOCR
      registry: ${{ secrets.DIGITALOCEAN_REGISTRY }}
      repository: ${{ secrets.DOCKER_IMAGE_PREFIX || 'invoice-manager' }}-backend
      tag: latest
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 5000
    routes:
      - path: /api
    envs:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        scope: RUN_TIME
        type: SECRET
      - key: PORT
        value: "5000"
    health_check:
      http_path: /api
      initial_delay_seconds: 30
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3

  - name: frontend
    image:
      registry_type: DOCR
      registry: ${{ secrets.DIGITALOCEAN_REGISTRY }}
      repository: ${{ secrets.DOCKER_IMAGE_PREFIX || 'invoice-manager' }}-frontend
      tag: latest
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 80
    routes:
      - path: /
    envs:
      - key: NODE_ENV
        value: production
    health_check:
      http_path: /
      initial_delay_seconds: 30
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3

